sudo: false
before_install:
  - gem update --system
  - gem install bundler
language: ruby
cache: bundler
rvm:
  - 2.3.6
  - 2.4.4
  - 2.5.3
  - 2.6.1
  - ruby-head
  - jruby-head
env:
  global:
    - CC_TEST_REPORTER_ID=7cf83cb3647a2969a1af2e1bbe49155388ad3a8ff45e6b0ec9be6c1c65ea9b96
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
